from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import ConfigDict
from sqlalchemy import (
    JSON,
    CheckConstraint,
    Column,
    ForeignKeyConstraint,
    Index,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, relationship
from sqlmodel import Field, Relationship, SQLModel

from core import get_settings
from utils.fields import (
    created_at_field,
    created_by_field,
    updated_at_field,
    updated_by_field,
)

APP_SCHEMA = get_settings().db_schema


def utc_now() -> datetime:
    """Return a timezone-naive UTC datetime for TIMESTAMP WITHOUT TIME ZONE columns."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


class JobStatus(str, Enum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'


class BaseSQLModel(SQLModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, from_attributes=True)  # type: ignore[bad-override]


class Document(BaseSQLModel, table=True):
    """Logical metadata document grouping jobs and metadata versions."""

    __tablename__ = 'documents'  # type: ignore[bad-argument-type]
    __table_args__ = ({'schema': APP_SCHEMA},)

    tenant_id: UUID = Field(primary_key=True)
    document_id: UUID = Field(primary_key=True)
    created_at: datetime = created_at_field()
    updated_at: datetime = updated_at_field()
    created_by: UUID = created_by_field()
    updated_by: UUID | None = updated_by_field()

    jobs: Mapped[list['Job']] = Relationship(
        sa_relationship=relationship(
            'Job',
            back_populates='document',
            cascade='all, delete-orphan',
            passive_deletes=True,
        )
    )
    metadata_versions: Mapped[list['DocumentMetadata']] = Relationship(
        sa_relationship=relationship(
            'DocumentMetadata',
            back_populates='document',
            cascade='all, delete-orphan',
            passive_deletes=True,
        )
    )


class Job(BaseSQLModel, table=True):
    """Metadata processing job as persisted in the metadata.metadata_jobs table."""

    __tablename__ = 'metadata_jobs'  # type: ignore[bad-argument-type]
    __table_args__ = (
        UniqueConstraint(
            'tenant_id',
            'document_id',
            'profile',
            'ingestion_fingerprint',
            name='uq_job_idempotency',
        ),
        CheckConstraint(
            "status in ('queued','running','succeeded','failed','canceled')",
            name='ck_metadata_jobs_status',
        ),
        Index('ix_jobs_status_priority_created', 'status', 'priority', 'created_at'),
        Index('ix_jobs_tenant_created', 'tenant_id', 'created_at'),
        ForeignKeyConstraint(
            ['tenant_id', 'document_id'],
            ['metadata.documents.tenant_id', 'metadata.documents.document_id'],
            name='fk_jobs_document',
            ondelete='CASCADE',
        ),
        {'schema': APP_SCHEMA},
    )

    job_id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID
    user_id: UUID
    document_id: UUID
    profile: str
    ingestion_fingerprint: str
    status: JobStatus = Field(
        default=JobStatus.QUEUED,
        sa_column=Column(
            String(20),
            nullable=False,
            server_default=JobStatus.QUEUED.value,
        ),
    )
    priority: int = Field(default=5)
    retries: int = Field(default=0)
    error_type: str | None = None
    error_msg: str | None = None
    created_at: datetime = created_at_field()
    updated_at: datetime = updated_at_field()
    created_by: UUID = created_by_field()
    updated_by: UUID | None = updated_by_field()
    started_at: datetime | None = None
    finished_at: datetime | None = None
    processing_fingerprint: str | None = None
    callback_url: str | None = None
    idempotency_key: str | None = None
    document_digest: str = Field(
        sa_column=Column(String(128), nullable=False),
        description='SHA256 digest for the source document.',
    )
    collection_name: str = Field(
        sa_column=Column(String(255), nullable=False),
        description='Vector store collection associated with the job.',
    )
    input_metadata: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description='Optional metadata provided with the job request.',
    )
    locked_fields: list[str] = Field(
        default_factory=list,
        sa_column=Column(JSON, nullable=False),
        description='Metadata fields that must not be overwritten by the agent.',
    )

    document: Mapped['Document'] = Relationship(sa_relationship=relationship('Document', back_populates='jobs'))


class DocumentMetadata(BaseSQLModel, table=True):
    """Versioned metadata payload generated by the agent."""

    __tablename__ = 'document_metadata'  # type: ignore[bad-argument-type]
    __table_args__ = (
        Index('ix_docmeta_tenant_doc_version', 'tenant_id', 'document_id', 'version', unique=True),
        ForeignKeyConstraint(
            ['tenant_id', 'document_id'],
            ['metadata.documents.tenant_id', 'metadata.documents.document_id'],
            name='fk_document_metadata_document',
            ondelete='CASCADE',
        ),
        {'schema': APP_SCHEMA},
    )

    tenant_id: UUID = Field(primary_key=True)
    document_id: UUID = Field(primary_key=True)
    version: int = Field(primary_key=True)
    fingerprint: str
    extracted_on: datetime = Field(default_factory=utc_now)
    created_at: datetime = created_at_field()
    updated_at: datetime = updated_at_field()
    created_by: UUID = created_by_field()
    updated_by: UUID | None = updated_by_field()
    payload: dict[str, Any] = Field(
        sa_column=Column(JSON, nullable=False),
        description='Full metadata payload as JSON.',
    )

    document: Mapped['Document'] = Relationship(
        sa_relationship=relationship('Document', back_populates='metadata_versions')
    )
